name: Cypress Tests
on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Set permissions
        run: chmod +x node_modules/.bin/cypress
      - name: Run Cypress tests
        run: npx cypress run
